[build]
  base = "frontend"
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  # REACT_APP_API_URL = "https://rawmart-assessment.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
